name: Main workflow
on: push
jobs:
  lint-js:
    name: Lint js with eslint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install

      - name: Lint with eslint
        run: yarn lint:js

  lint-styles:
    name: Lint styles with stylelint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install

      - name: Lint with stylelint
        run: yarn lint:styles

  types:
    name: Check types
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install

      - name: Check types with tsc
        run: yarn check-types

  test:
    name: Test with jest
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install

      - name: Test with jest
        run: yarn test

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install

      - name: Build production
        run: yarn build

  deploy:
    name: Deploy prod
    runs-on: ubuntu-20.04
#    if: github.ref == 'refs/heads/master'
    needs: [lint-js, lint-styles, types, test, build]
    env:
      REACT_APP_SENTRY_DSN: ${{secrets.REACT_APP_SENTRY_DSN}}
      REACT_APP_MIXPANEL_ID: ${{secrets.REACT_APP_MIXPANEL_ID}}
      REACT_APP_MIXPANEL_PROXY_HOST: ${{secrets.REACT_APP_MIXPANEL_PROXY_HOST}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install

      - name: Build production
        run: yarn build

      - name: Deploy production
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true
